class Vendedor():
    def __init__(self, nome):
        self.nome = nome  #Printar os valores do Objeto nome.vendas...
        self.vendas = 0
    
    def vendeu(self, vendas):  #atribuir valores para o Objeto .vendeu...
        self.vendas = vendas  #Printar os valores do Objeto nome.vendas...
    
    def meta(self, meta):  #atribuir valores para o Objeto .vendeu...
        if self.vendas >= meta:
            print(self.nome, 'Bateu a Meta de', meta)
        else:
            print(self.nome, 'Não bateu a meta', meta)


vendedor01 = Vendedor('Matheus') #atribuir valores para o Objeto .vendeu...
vendedor01.vendeu(1000)  #atribuir valores para o Objeto .vendeu...

print(vendedor01.nome)  #Printar os valores do Objeto nome.nome...
print(vendedor01.vendas)  #Printar os valores do Objeto nome.vendas...
vendedor01.meta(750)  #atribuir valores para o Objeto .meta porem a função já retorna um print...




